image: "ubuntu:latest"

variables:
  TEST: "TZ=America/Chicago"


before_script:
  - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
  - apt update
  - apt install -y build-essential
  - apt install -y clang valgrind cppcheck

stages:
  - Static Analysis

clang_sanatizer:
  stage: Static Analysis
  allow_failure: true
  script:
    - gcc -O1 -ggdb -fsanitize=address -fno-omit-frame-pointer -static-libstdc++ -static-libasan -lrt *.c

valgrind_memcheck:
  stage: Static Analysis
  allow_failure: true
  script:
    - gcc -g -O2 *.c -o fuzzer
    - valgrind --tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=20 --track-fds=yes ./fuzzer

run_cppcheck:
  stage: Static Analysis
  allow_failure: true
  script:
    - cppcheck --enable=all  --check-config --suppress=missingIncludeSystem main.c

